name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: ["ubuntu-latest"]
        php-versions: ["8.2","8.3"]

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6 # or alternative dependency management
    - run: composer install
    - run: ./vendor/bin/phpunit
